# Generated by Django 3.2 on 2022-06-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='blog_img'),
        ),
    ]
